
		
			BSF		PORT, LATCH
			BCF		PORT, LATCH
LOOP_CTRL	BSF		PORT, PULSE
			BCF		PORT, PULSE
			INCF	CONT_AUX, F
			MOVF	CONT_AUX, W
			XORLW	0x04			;Me fijo para ARRIBA
			BTFSC	STATUS, Z
			GOTO	CHECK_DATA
			XORLW	0x05			;Me fijo para ABAJO
			BTFSC	STATUS, Z
			GOTO	CHECK_DATA
			GOTO	LOOP_CTRL
CHECK_DATA	BTFSS	PORT, DATA		;Si data es 0, se presiono
			GOTO	MOVERPALETA
			BTFSC	CONT_AUX, 0		;Si me fije abajo me voy
			RETURN
			GOTO	LOOP_CTRL